services:
  db:
    image: postgres:16.2-alpine
    command: -p 5432
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
    networks:
      - backend
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/
    networks:
      - backend
volumes:
  db-data:

networks:
  backend:
    driver: bridge