services:
  db:
    image: postgres:16.2-alpine
    command: -p 5432
    expose:
      - 5432
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=password
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/
