"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tsF67k9Kcau
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Link from "next/link";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuSeparator,
  DropdownMenuItem,
} from "@/components/ui/dropdown-menu";
import { Mountain, LogOut, Settings, User as UserIcon } from "lucide-react";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import useUserContext from "./user-context";
import { redirect } from "next/navigation";
import User from "@/lib/models/user";

export function Header() {
  const { user, setUser } = useUserContext();

  return (
    <header className="flex items-center justify-between px-4 py-3 bg-white shadow dark:bg-slate-950">
      <Link href="/" className="flex items-center gap-2" prefetch={false}>
        <Mountain className="h-6 w-6" />
        <span className="text-lg font-bold">Twotty</span>
      </Link>
      {user && <HeaderDropdownMenu user={user} />}
    </header>
  );
  ``;
}

function HeaderDropdownMenu({ user }: { user: User }) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Avatar className="h-9 w-9 cursor-pointer">
          <AvatarImage
            src={user?.avatar ? user.avatar : "/placeholder-user.jpg"}
          />
          {/* <AvatarFallback>USER</AvatarFallback> */}
        </Avatar>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        <DropdownMenuItem>
          <Link
            href={"/user/" + user.username}
            className="flex items-center gap-2"
            prefetch={false}
          >
            <UserIcon className="h-4 w-4" />
            Profile
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem>
          <Link
            href="/settings"
            className="flex items-center gap-2"
            prefetch={false}
          >
            <Settings className="h-4 w-4" />
            Settings
          </Link>
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem>
          <Link
            href="/logout"
            className="flex items-center gap-2"
            prefetch={false}
          >
            <LogOut className="h-4 w-4" />
            Logout
          </Link>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
