"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cSK1wK8fG7M
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import Post from "@/lib/models/post";
import User from "@/lib/models/user";
import { Post as PostCard } from "./post";
import { useState } from "react";
import { createPost, getUserPosts } from "@/lib/api";
import useUserContext from "./user-context";
import { redirect } from "next/navigation";

export function UserProfile({
  author,
  posts,
  setPosts,
}: {
  author: User;
  posts: [Post];
  setPosts: any;
}) {
  const { user, setUser } = useUserContext();
  const [message, setMessage] = useState("");

  console.log(user?.id, author.id);

  if (!user) {
    redirect("/login");
  }

  async function handleSubmit(e: any) {
    e.preventDefault();
    await createPost(message);
    const userPosts = await getUserPosts(author.username);
    setPosts(userPosts);
    setMessage("");
  }

  return (
    <div className="grid md:grid-cols-[300px_1fr] gap-8 max-w-6xl mx-auto px-4 py-8">
      <div className="flex flex-col items-center gap-4">
        <Avatar className="w-24 h-24 dark:border-slate-50">
          <AvatarImage
            src={author.avatar ? author.avatar : "/placeholder-user.jpg"}
          />
          <AvatarFallback>JD</AvatarFallback>
        </Avatar>
        <div className="text-center">
          <div className="text-2xl font-bold">@{author.username}</div>
          {/* <div className="text-slate-500 dark:text-slate-400">@johndoe</div> */}
          <div className="text-muted-foreground mt-2">{author.about}</div>
        </div>
      </div>
      <div className="grid gap-6">
        {user.id == author.id && (
          <div className="grid gap-4">
            <Textarea
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              className="p-4 min-h-[100px] rounded-md border focus:border-primary focus:ring-primary"
              placeholder="Write a new post..."
            />
            <Button onClick={handleSubmit} className="ml-auto">
              Post
            </Button>
          </div>
        )}
        <div className="grid gap-4">
          {posts.map((post) => {
            return (
              <PostCard
                key={post.id}
                id={post.id}
                text={post.text}
                edited={post.edited}
                createdAt={post.createdAt}
                author={author}
                currentUser={user}
                setPosts={setPosts}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
}
