/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cSK1wK8fG7M
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import Post from "@/lib/models/post";
import User from "@/lib/models/user";
import { Post as PostCard } from "./post";

export function UserProfile({ user, posts }: { user: User; posts: [Post] }) {
  return (
    <div className="grid md:grid-cols-[300px_1fr] gap-8 max-w-6xl mx-auto px-4 py-8">
      <div className="flex flex-col items-center gap-4">
        <Avatar className="w-24 h-24 dark:border-slate-50">
          <AvatarImage
            src={user.avatar ? user.avatar : "/placeholder-user.jpg"}
          />
          <AvatarFallback>JD</AvatarFallback>
        </Avatar>
        <div className="text-center">
          <div className="text-2xl font-bold">@{user.username}</div>
          {/* <div className="text-slate-500 dark:text-slate-400">@johndoe</div> */}
        </div>
      </div>
      <div className="grid gap-6">
        <div className="grid gap-4">
          {posts.map((post) => {
            return (
              <PostCard
                key={post.id}
                text={post.text}
                edited={post.edited}
                createdAt={post.createdAt}
                user={user}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
}
